version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
  settings:
    depguard:
      rules:
        main:
          list-mode: original
          files:
            - '**/*.go'
          allow:
            - $gostd
            - github.com/adamvduke/vigil/client
            - github.com/adamvduke/vigil/proto/vigilpb
            - github.com/adamvduke/vigil/watcher
            - github.com/fsnotify/fsnotify
            - github.com/vrecan/death/v3
            - google.golang.org/grpc
            - google.golang.org/grpc/credentials/insecure
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*bytes.Buffer).WriteString
    gocognit:
      min-complexity: 15
    gocritic:
      enable-all: true
    gocyclo:
      min-complexity: 10
    godot:
      scope: toplevel
      exclude:
        - '^fixme:'
        - '^todo:'
      capital: true
      period: true
    gosec:
      excludes:
        - G204 # Subprocess launched with a potential tainted input or cmd arguments
    lll:
      line-length: 140
      tab-width: 1
    nestif:
      min-complexity: 5
    nlreturn:
      block-size: 10
    staticcheck:
      checks:
        - all
    varnamelen:
      max-distance: 5
      min-name-length: 3
      check-receiver: true
      check-return: true
      check-type-param: true
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
    whitespace:
      multi-if: true
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/adamvduke/vigil)
        - prefix(github.com)
        - prefix(google.golang.org)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
