// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: vigil.proto

package vigilpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddWatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path *string `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
}

func (x *AddWatchRequest) Reset() {
	*x = AddWatchRequest{}
	mi := &file_vigil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchRequest) ProtoMessage() {}

func (x *AddWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vigil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchRequest.ProtoReflect.Descriptor instead.
func (*AddWatchRequest) Descriptor() ([]byte, []int) {
	return file_vigil_proto_rawDescGZIP(), []int{0}
}

func (x *AddWatchRequest) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type AddWatchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message      *string  `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	WatchedPaths []string `protobuf:"bytes,2,rep,name=watched_paths,json=watchedPaths,proto3" json:"watched_paths,omitempty"`
}

func (x *AddWatchReply) Reset() {
	*x = AddWatchReply{}
	mi := &file_vigil_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWatchReply) ProtoMessage() {}

func (x *AddWatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_vigil_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWatchReply.ProtoReflect.Descriptor instead.
func (*AddWatchReply) Descriptor() ([]byte, []int) {
	return file_vigil_proto_rawDescGZIP(), []int{1}
}

func (x *AddWatchReply) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *AddWatchReply) GetWatchedPaths() []string {
	if x != nil {
		return x.WatchedPaths
	}
	return nil
}

type WatchedPathsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WatchedPathsRequest) Reset() {
	*x = WatchedPathsRequest{}
	mi := &file_vigil_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchedPathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchedPathsRequest) ProtoMessage() {}

func (x *WatchedPathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vigil_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchedPathsRequest.ProtoReflect.Descriptor instead.
func (*WatchedPathsRequest) Descriptor() ([]byte, []int) {
	return file_vigil_proto_rawDescGZIP(), []int{2}
}

type WatchedPathsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *WatchedPathsReply) Reset() {
	*x = WatchedPathsReply{}
	mi := &file_vigil_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchedPathsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchedPathsReply) ProtoMessage() {}

func (x *WatchedPathsReply) ProtoReflect() protoreflect.Message {
	mi := &file_vigil_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchedPathsReply.ProtoReflect.Descriptor instead.
func (*WatchedPathsReply) Descriptor() ([]byte, []int) {
	return file_vigil_proto_rawDescGZIP(), []int{3}
}

func (x *WatchedPathsReply) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_vigil_proto protoreflect.FileDescriptor

var file_vigil_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x76, 0x69, 0x67, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x22, 0x5f, 0x0a, 0x0d, 0x41, 0x64, 0x64,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0d, 0x77, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x73, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x29, 0x0a, 0x11, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x32, 0x8d, 0x01, 0x0a,
	0x07, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x50,
	0x61, 0x74, 0x68, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64,
	0x50, 0x61, 0x74, 0x68, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x76, 0x69, 0x67, 0x69, 0x6c, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vigil_proto_rawDescOnce sync.Once
	file_vigil_proto_rawDescData = file_vigil_proto_rawDesc
)

func file_vigil_proto_rawDescGZIP() []byte {
	file_vigil_proto_rawDescOnce.Do(func() {
		file_vigil_proto_rawDescData = protoimpl.X.CompressGZIP(file_vigil_proto_rawDescData)
	})
	return file_vigil_proto_rawDescData
}

var file_vigil_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vigil_proto_goTypes = []any{
	(*AddWatchRequest)(nil),     // 0: proto.AddWatchRequest
	(*AddWatchReply)(nil),       // 1: proto.AddWatchReply
	(*WatchedPathsRequest)(nil), // 2: proto.WatchedPathsRequest
	(*WatchedPathsReply)(nil),   // 3: proto.WatchedPathsReply
}
var file_vigil_proto_depIdxs = []int32{
	0, // 0: proto.Watcher.AddWatch:input_type -> proto.AddWatchRequest
	2, // 1: proto.Watcher.WatchedPaths:input_type -> proto.WatchedPathsRequest
	1, // 2: proto.Watcher.AddWatch:output_type -> proto.AddWatchReply
	3, // 3: proto.Watcher.WatchedPaths:output_type -> proto.WatchedPathsReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vigil_proto_init() }
func file_vigil_proto_init() {
	if File_vigil_proto != nil {
		return
	}
	file_vigil_proto_msgTypes[0].OneofWrappers = []any{}
	file_vigil_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vigil_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vigil_proto_goTypes,
		DependencyIndexes: file_vigil_proto_depIdxs,
		MessageInfos:      file_vigil_proto_msgTypes,
	}.Build()
	File_vigil_proto = out.File
	file_vigil_proto_rawDesc = nil
	file_vigil_proto_goTypes = nil
	file_vigil_proto_depIdxs = nil
}
